# Generated by Django 4.2.7 on 2023-11-29 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='city',
            new_name='location',
        ),
    ]
