# Generated by Django 4.2.7 on 2024-10-08 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('TSHIRT', 'TSHIRT'), ('HOODIE', 'HOODIE'), ('SWEATSHIRT', 'SWEATSHIRT'), ('BEANIE', 'BEANIE'), ('MUG', 'MUG'), ('HAT', 'HAT')], max_length=50),
        ),
    ]
